#import './Pic/fragment.gql'
#import './Form/fragment.gql'
#import './PictureEditModal/fragment.gql'

query Product($id: ID!) {
  product(id: $id) {
    id
    title {
      en
      ru
    }
    state
    ...Form
    pictures {
      id
      ...PictureEditModal
    }
  }
}