/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ConfigIndex {
  builderToken: string;
  client_url: string;
  google_sign_in_button: GoogleSignInButtonConfig;
  granted_emails: string[];
  imagesFolder: string;
  insta: InstaConfig;
  jwt: JWTConfig;
  publicSite: PublicSiteConfig;
  storeFolder: string;
}

export interface GoogleSignInButtonConfig {
  client_id: string;
}

export interface InstaConfig {
  access_token: string;
  instagram_id: string;
}

export interface JWTConfig {
  cert?: string;
  privateKey?: string;
  private_key_filename: string;
  public_key_filename: string;
  token_lifespan: number;
}

export interface PublicSiteConfig {
  folder: string;
}
