name: CI

on: [push]

jobs:
  build:
    name: Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Save config
        run: |
          echo "$CONFIG" >> config.json
        shell: bash
        env:
          CONFIG: ${{secrets.CONFIG}}
      - name: Build
        run: docker build -t ghcr.io/tyorka-shop/admin.tyorka.com:latest .

      - name: Publish
        run: docker push ghcr.io/tyorka-shop/admin.tyorka.com:latest
