name: CI

on: [push]

jobs:
  build:
    name: Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Save config
        run: |
          echo "$CONFIG" >> config.json
        shell: bash
        env:
          CONFIG: ${{secrets.CONFIG}}

      - name: Save .npmrc
        run: |
          echo "$NPMRC" >> .npmrc
        shell: bash
        env:
          CONFIG: ${{secrets.NPMRC}}

      - name: Install deps
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      
      - name: Publish
        run: npm publish
